monolog:
  #
  # Set new logger to log statistics information to ES.
  #
  channels: ["statistics"]
  handlers:
    statistics:
      type: elasticsearch
      elasticsearch:
        host: '%env(ESASTICA_HOST)%'
        port: '%env(ESASTICA_PORT)%'
      index: '%env(ES_STATS_INDEX)%'
      channels: ["statistics"]
