services:
  monolog.elastica.client:
    # @TODO use official client instead of Ruflin\Elastica\Client
    # (Symfony 5 supports Monolog 2 which supports the official client)
    class: Elastica\Client
    arguments:
      # Ruflin\Elastica\Client used by monolog requires trailing slash
      $config: { url: '%env(ELASTIC_URL)%/' }

monolog:
  #
  # Set new logger to log statistics information to ES.
  #
  channels: ["statistics"]
  handlers:
    statistics:
      type: elasticsearch
      elasticsearch:
        id: monolog.elastica.client
      index: '%env(append_date:ELASTIC_STATS_INDEX_PREFIX)%'
      channels: ["statistics"]
