apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  namespace: cover-service
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # production
    #server: https://acme-staging-v02.api.letsencrypt.org/directory # staging
    email: itkdev@mkb.aarhus.dk
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class:  nginx