---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-configmap
data:
  APP_CORS_ALLOW_ORIGIN: '{{ .Values.app.cors_allow_origin }}'
  APP_REDIS_SERVER: 'redis'
  APP_REDIS_PORT: '6379'
  APP_REDIS_CACHE_SERVER: 'redis'
  APP_REDIS_CACHE_PORT: '6379'
  APP_REDIS_CACHE_DB: '10'
  APP_ELASTIC_URL: 'http://elasticsearch-es-http:9200/'
  APP_ENABLE_NO_HITS: 'false'
  PHP_PM_MAX_CHILDREN: '80'
  PHP_PM_START_SERVERS: '15'
  PHP_PM_MIN_SPARE_SERVERS: '15'
  PHP_PM_MAX_SPARE_SERVERS: '30'
  PHP_REQUEST_SLOWLOG_TIMEOUT: '1'

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: nginx-config
data:
  PHP_FPM_SERVER: '127.0.0.1'
  PHP_FPM_SERVER_PORT: '9000'