---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-app
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
        tier: frontend
        #path: {{ .Values.ingress.path | quote }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/scheme: 'http'
        # Ensure rolling updates on config changes.
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: symfony-phpfpm
          image: danskernesdigitalebibliotek/cover-service:{{ .Values.app.image.version }}
          imagePullPolicy: {{ .Values.app.image.imagePullPolicy }}
          resources:
            requests:
              memory: '512Mi'
              cpu: '100m'
            limits:
              memory: '638Mi'
              cpu: '300m'
          readinessProbe:
            exec:
              command:
                - php-fpm-healthcheck
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - php-fpm-healthcheck
                - --accepted-conn=50000
            initialDelaySeconds: 0
            periodSeconds: 10
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: APP_SECRET
            - name: APP_OPENPLATFORM_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: APP_OPENPLATFORM_ID
            - name: APP_OPENPLATFORM_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: APP_OPENPLATFORM_SECRET
            - name: APP_AMQP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: APP_AMQP_USERNAME
            - name: APP_AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: APP_AMQP_PASSWORD
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          ports:
            - containerPort: 9000
            - containerPort: 9253
        - name: nginx
          image: danskernesdigitalebibliotek/cover-service-nginx:{{ .Values.app.image.version }}
          imagePullPolicy: {{ .Values.app.image.imagePullPolicy }}
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '96Mi'
              cpu: '200m'
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-nginx-config
          ports:
            - containerPort: 8080
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:{{ .Values.nginx.exporter.image.version }}
          imagePullPolicy: {{ .Values.app.image.imagePullPolicy }}
          args:
            - "-nginx.scrape-uri=http://127.0.0.1:8081/stub_status"
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '96Mi'
              cpu: '100m'
          readinessProbe:
            tcpSocket:
              port: 9113
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9113
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 9113
