---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Namespace }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.app.cors_allow_origin }}"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
      secretName: {{ .Release.Namespace }}-ingress-tls-secret
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Namespace }}-service
              servicePort: 80
            path: /