---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: {{ .Release.Namespace }}
  name: letsencrypt
spec:
  acme:
    {{- if eq .Values.cert.env "prod" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    email: {{ .Values.cert.mail | quote }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
