---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace:  {{ .Release.Namespace }}
  name: redis-config
data:
  redis.conf: |
    maxmemory {{ .Values.redis.maxmemory }}
    databases 16
    maxmemory-policy allkeys-lru

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace:  {{ .Release.Namespace }}
  name: redis-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.storage.class }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}

---
apiVersion: v1
kind: Service
metadata:
  namespace:  {{ .Release.Namespace }}
  name: redis
  labels:
    tier: backend
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace:  {{ .Release.Namespace }}
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      containers:
      - name: redis
        image: redis:{{ .Values.redis.version }}
        command:
          - redis-server
          - "/etc/redis/redis.conf"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        volumeMounts:
          - mountPath: /data
            name: data
          - mountPath: /etc/redis/
            name: config
        env:
          - name: MASTER
            value: "true"
        ports:
          - containerPort: 6379
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.5.2-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 9121
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-managed-disk
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf