---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: cover-service
  name: cover-service-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  tls:
    - hosts:
        - coverservice.itkdev.dk
      secretName: cover-service-frontend-tls-secret
  rules:
    - host: coverservice.itkdev.dk
      http:
        paths:
          - backend:
              serviceName: cover-service
              servicePort: 80
            path: /