version: "3"

networks:
  web:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      #- ENCRYPT=1 # Uncomment to enable database encryption.

  phpfpm:
    image: itkdev/php8.1-fpm
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_XDEBUG_MODE=${PHP_XDEBUG_MODE:-off}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      # - PHP_MAIL=1 # Uncomment to enable mailhog.
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - COMPOSER_VERSION=2
      - PHP_IDE_CONFIG=serverName=localhost
      # Send all container trafik though proxy, useful for testing.
    #      - HTTP_PROXY=host.docker.internal:8090
    #      - HTTPS_PROXY=host.docker.internal:8090
    depends_on:
      - mariadb
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    networks:
      - app
      - web
    depends_on:
      - phpfpm
    ports:
      - '80'
    volumes:
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  redis:
    image: 'redis:6'
    networks:
      - app
    ports:
      - '6379'

  elasticsearch:
    image: 'opensearchproject/opensearch:2'
    networks:
      - app
    environment:
      - name=opensearch-node2
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=ihBDx2atXZjpgYWaEy9c
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    ports:
      - '9200'

  rabbit:
    image: rabbitmq:3.9-management
    networks:
      - app
      - web
    ports:
      - '15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE='d53f319cd7376f8f840aaf9889f315ab'

volumes:
  opensearch-data2:
    driver: local
