# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: {url: '%env(ELASTIC_URL)%', ssl: '%env(bool:ELASTIC_SSL)%', username: '%env(ELASTIC_USERNAME)%', password: '%env(ELASTIC_PASSWORD)%', curl: {64: '%env(bool:ELASTIC_SSL_VERIFY)%', 81: '%env(bool:ELASTIC_SSL_VERIFY)%'}}
    indexes:
        app:
            index_name: app_%kernel.environment%
            types:
                search:
                    properties:
                        isIdentifier: {type:  keyword}
                        isType: {type:  keyword}
                        imageUrl: ~
                        imageFormat: {type:  keyword}
                        width: ~
                        height: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Search
                        provider: ~
                        finder: ~
                        repository: App\Repository\SearchRepository
                        elastica_to_model_transformer:
                            ignore_missing: true
