# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        filesystem_adapter:
            local:
                directory: '%kernel.cache_dir%/flysystem'
        bogportalen_ftp:
            ftp:
                host: ''
                username: ''
                password: ''
                root: 'Public'
                ssl: false
        bogportalen_zip:
            zip:
                location: "%kernel.cache_dir%/flysystem/BOP-ProductAll.zip"
    filesystems:
        local:
            adapter: filesystem_adapter
            alias: League\Flysystem\Filesystem

        bogportalen_ftp:
            adapter: bogportalen_ftp

        bogportalen_local_zip:
            adapter: bogportalen_zip
