version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  phpfpm:
    image: itkdev/php8.1-fpm
    networks:
      - app
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - PHP_IDE_CONFIG=serverName=localhost
      - PHP_APCU_ENABLED=1
      - PHP_APCU_ENABLED_CLI=1
      - COMPOSER_VERSION=2
    depends_on:
      - elasticsearch
    volumes:
      - .:/app:delegated

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - '8080'
    volumes:
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  redis:
    image: 'redis:6'
    networks:
      - app
    ports:
      - '6379'

  rabbit:
    image: rabbitmq:3.9-management
    networks:
      - app
      - frontend
    ports:
      - 15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE='d53f319cd7376f8f840aaf9889f315ab'

  elasticsearch:
    image: 'opensearchproject/opensearch:2'
    networks:
      - app
    environment:
      - name=opensearch-node1
      - discovery.type=single-node
      - plugins.security.disabled=true
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - '9200'

volumes:
  opensearch-data1:
    driver: local
