# A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
# with the app.

cover-api:

  # The runtime the application uses. The 'type' key defines the base container
  # image that will be used to run the application. There is a separate base
  # container image for each primary language for the application,
  # in multiple versions. Check the PHP documentation
  # (https://docs.platform.sh/languages/php.html#supported-versions)
  # to find the supported versions for the 'php' type.
  type: 'php:8.1'

  # The size of the persistent disk of the application (in MB).
  disk: 256

  build:
    flavor: composer

  dependencies:
    php:
      composer/composer: '^2'

  variables:
    php:
      opcache.preload: config/preload.php
    env:
      APP_ENV: 'dev'
      APP_DEBUG: 1

  # The 'source' specifies where the writable mount is. The 'local' source
  # indicates that the mount point will point to a local directory on the
  # application container. The 'source_path' specifies the subdirectory
  # from within the source that the mount should point at.
  # The mounts that will be performed when the package is deployed.
  mounts:
    "/var/cache":
      source: local
      source_path: "cache"
    "/var/log":
      source: local
      source_path: "log"
    "/var/sessions":
      source: local
      source_path: "sessions"

  # The relationships of the application with services or other applications.
  #
  # The left-hand side is the name of the relationship as it will be exposed
  # to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
  # side is in the form '<service name>:<endpoint name>'.
  relationships:
    # TODO:    essearch: 'searchelastic:elasticsearch'
    rabbit: 'queuerabbit:rabbitmq'
    redis: 'cachecoverapi:redis'

  hooks:
    build: |
      set -x -e
      curl -s https://get.symfony.com/cloud/configurator | bash
      symfony-build

    deploy: |
      set -x -e    
      symfony-deploy        

  # The configuration of app when it is exposed to the web.
  web:
    locations:
      "/":
        # The public directory of the app, relative to its root.
        root: "public"
        # The front-controller script to send non-static requests to.
        passthru: "/index.php"

  # Customizations to your PHP or Lisp runtime. More information: https://docs.platform.sh/create-apps/app-reference.html#runtime
  runtime:
    extensions:
      - apcu
      - blackfire
      - ctype
      - iconv
      - mbstring
      - pdo_pgsql
      - sodium
      - xsl
      - amqp
      - redis

  # Information on the app's source code and operations that can be run on it.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#source
  source:
    # The path where the app code lives. Defaults to the directory of the .platform.app.yaml file. Useful for multi-app setups.
    root: cover-api

importers:

  # The runtime the application uses. The 'type' key defines the base container
  # image that will be used to run the application. There is a separate base
  # container image for each primary language for the application,
  # in multiple versions. Check the PHP documentation
  # (https://docs.platform.sh/languages/php.html#supported-versions)
  # to find the supported versions for the 'php' type.
  type: 'php:8.1'

  # The size of the persistent disk of the application (in MB).
  disk: 256

  build:
    flavor: composer

  dependencies:
    php:
      composer/composer: '^2'

  variables:
    php:
      opcache.preload: config/preload.php
    env:
      APP_ENV: 'dev'
      APP_DEBUG: 1

  # The 'source' specifies where the writable mount is. The 'local' source
  # indicates that the mount point will point to a local directory on the
  # application container. The 'source_path' specifies the subdirectory
  # from within the source that the mount should point at.
  # The mounts that will be performed when the package is deployed.
  mounts:
    "/var/cache":
      source: local
      source_path: "cache"
    "/var/log":
      source: local
      source_path: "log"
    "/var/sessions":
      source: local
      source_path: "sessions"
    "resources":
      source: local
      source_path: "resources"

  # The relationships of the application with services or other applications.
  # The left-hand side is the name of the relationship as it will be exposed
  # to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
  # side is in the form `<service name>:<endpoint name>`.
  relationships:
    database: 'dbimporters:mysql'
    redis: 'cacheimporters:redis'
    rabbit: 'queuerabbit:rabbitmq'

  hooks:
    build: |
      set -x -e
      curl -s https://get.symfony.com/cloud/configurator | bash
      symfony-build

    deploy: |
      set -x -e    
      symfony-deploy        

  # Scheduled tasks for the app.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#crons
  crons:
    # Run nightly imports of vendors.
    import-vendors:
      spec: '0 1 * * 1-6'
      # TODO: Set vendors - how?
      cmd: './bin/console app:vendor:load --env=prod --no-debug --days-ago=180 --vendor=none'

  # The configuration of app when it is exposed to the web.
  web:
    locations:
      "/":
        # The public directory of the app, relative to its root.
        root: "public"
        # The front-controller script to send non-static requests to.
        passthru: "/index.php"

  workers:
    messenger:
      commands:
        # Consume "async_priority_high", "async_priority_low", "async_has_cover" & "async_no_hit"
        # messages (as configured in the routing section of config/packages/messenger.yaml)
        start: symfony console --time-limit=3600 --memory-limit=64M messenger:consume --env=prod --no-debug --no-interaction --quiet --failure-limit=1 async_priority_high async_priority_low async_has_cover async_no_hit

  # Customizations to your PHP or Lisp runtime. More information: https://docs.platform.sh/create-apps/app-reference.html#runtime
  runtime:
    extensions:
      - apcu
      - blackfire
      - ctype
      - iconv
      - mbstring
      - pdo_pgsql
      - sodium
      - xsl
      - amqp
      - redis

  # Information on the app's source code and operations that can be run on it.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#source
  source:
    # The path where the app code lives. Defaults to the directory of the .platform.app.yaml file. Useful for multi-app setups.
    root: importers

upload-api:

  # The runtime the application uses. The 'type' key defines the base container
  # image that will be used to run the application. There is a separate base
  # container image for each primary language for the application,
  # in multiple versions. Check the PHP documentation
  # (https://docs.platform.sh/languages/php.html#supported-versions)
  # to find the supported versions for the 'php' type.
  type: 'php:8.1'

  # The size of the persistent disk of the application (in MB).
  disk: 256

  build:
    flavor: composer

  dependencies:
    php:
      composer/composer: '^2'

  variables:
    php:
      opcache.preload: config/preload.php
    env:
      APP_ENV: 'dev'
      APP_DEBUG: 1

  # The 'source' specifies where the writable mount is. The 'local' source
  # indicates that the mount point will point to a local directory on the
  # application container. The 'source_path' specifies the subdirectory
  # from within the source that the mount should point at.
  # The mounts that will be performed when the package is deployed.
  mounts:
    "/var/cache":
      source: local
      source_path: "cache"
    "/var/log":
      source: local
      source_path: "log"
    "/var/sessions":
      source: local
      source_path: "sessions"

      # TODO: path?
    "UploadService":
      source: local
      source_path: "UploadService"

  # The relationships of the application with services or other applications.
  #
  # The left-hand side is the name of the relationship as it will be exposed
  # to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
  # side is in the form '<service name>:<endpoint name>'.
  relationships:
    database: 'dbuploadapi:mysql'
    rabbit: 'queuerabbit:rabbitmq'
    redis: 'cacheuploadapi:redis'

  hooks:
    build: |
      set -x -e
      curl -s https://get.symfony.com/cloud/configurator | bash
      symfony-build

    deploy: |
      set -x -e    
      symfony-deploy        

  # Scheduled tasks for the app.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#crons
  crons:
    # Cover service upload clean up cron job.
    image-cleanup:
      spec: '*/15 * * * *'
      cmd: './bin/console app:image:cleanup --no-debug'

  # The configuration of app when it is exposed to the web.
  web:
    locations:
      "/":
        # The public directory of the app, relative to its root.
        root: "public"
        # The front-controller script to send non-static requests to.
        passthru: "/index.php"

  # Customizations to your PHP or Lisp runtime. More information: https://docs.platform.sh/create-apps/app-reference.html#runtime
  runtime:
    extensions:
      - apcu
      - blackfire
      - ctype
      - iconv
      - mbstring
      - pdo_pgsql
      - sodium
      - xsl
      - amqp
      - redis

  # Information on the app's source code and operations that can be run on it.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#source
  source:
    # The path where the app code lives. Defaults to the directory of the .platform.app.yaml file. Useful for multi-app setups.
    root: upload-api
