# Each route describes how an incoming URL is going to be processed by Platform.sh.

https://{default}/:
  type: upstream
  upstream: "cover-api:http"
  id: cover-api

https://importers.{default}/:
  type: upstream
  upstream: "importers:http"
  id: importers

https://upload.{default}/:
  type: upstream
  upstream: "upload-api:http"
  id: upload-api

"http://{default}/":
  type: redirect
  to: "https://{default}/"

"http://importers.{default}/":
  type: redirect
  to: "https://importers.{default}/"

"http://upload.{default}/":
  type: redirect
  to: "https://upload.{default}/"
