# The name given to the Elasticsearch service (lowercase alphanumeric only).

# TODO:
#searchelastic:
#  # The type of your service (elasticsearch), which uses the format
#  # 'type:version'. Be sure to consult the Elasticsearch documentation
#  # (https://docs.platform.sh/add-services/elasticsearch.html#supported-versions)
#  # when choosing a version. If you specify a version number which is not available,
#  # the CLI will return an error.
#  type: elasticsearch:8.5
#  # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
#  disk: 256

# The name given to the RabbitMQ service (lowercase alphanumeric only).
queuerabbit:
  # The type of your service (rabbitmq), which uses the format
  # 'type:version'. Be sure to consult the RabbitMQ documentation
  # (https://docs.platform.sh/add-services/rabbitmq.html#supported-versions)
  # when choosing a version. If you specify a version number which is not available,
  # the CLI will return an error.
  type: rabbitmq:3.9
  # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
  disk: 512

# The name given to the Redis service (lowercase alphanumeric only).
cachecoverapi:
  # The type of your service (redis), which uses the format
  # 'type:version'. Be sure to consult the Redis documentation
  # (https://docs.platform.sh/add-services/redis.html#supported-versions)
  # when choosing a version. If you specify a version number which is not available,
  # the CLI will return an error.
  type: redis:6.2

# The name given to the Redis service (lowercase alphanumeric only).
cacheimporters:
  # The type of your service (redis), which uses the format
  # 'type:version'. Be sure to consult the Redis documentation
  # (https://docs.platform.sh/add-services/redis.html#supported-versions)
  # when choosing a version. If you specify a version number which is not available,
  # the CLI will return an error.
  type: redis:6.2

# The name given to the Redis service (lowercase alphanumeric only).
cacheuploadapi:
  # The type of your service (redis), which uses the format
  # 'type:version'. Be sure to consult the Redis documentation
  # (https://docs.platform.sh/add-services/redis.html#supported-versions)
  # when choosing a version. If you specify a version number which is not available,
  # the CLI will return an error.
  type: redis:6.2

# The name given to the MariaDB/MySQL service (lowercase alphanumeric only).
dbimporters:
  # The type of your service (mariadb), which uses the format
  # 'type:version'. Be sure to consult the MariaDB/MySQL documentation
  # (https://docs.platform.sh/add-services/mysql.html#supported-versions)
  # when choosing a version. If you specify a version number which is not available,
  # the CLI will return an error.
  type: mariadb:10.6
  # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
  disk: 256

# The name given to the MariaDB/MySQL service (lowercase alphanumeric only).
dbuploadapi:
  # The type of your service (mariadb), which uses the format
  # 'type:version'. Be sure to consult the MariaDB/MySQL documentation
  # (https://docs.platform.sh/add-services/mysql.html#supported-versions)
  # when choosing a version. If you specify a version number which is not available,
  # the CLI will return an error.
  type: mariadb:10.6
  # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
  disk: 256
