on: pull_request
name: Review
jobs:
    test-composer-install:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.4']
        name: Validate composer (${{ matrix.php}})
        steps:
            - uses: actions/checkout@master

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php}}
                tools: composer:v1
                extensions: apcu, ctype, iconv, imagick, json, redis, soap, xmlreader, zip
                coverage: none

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v1
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: ${{ matrix.php }}-composer-

            - name: Validate composer files
              run: composer validate composer.json

            - name: Composer install with exported .env variables
              run: |
                  set -a && source .env && set +a
                  APP_ENV=prod composer install --no-dev -o

    unit_tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.4']
        name: Unit tests (${{ matrix.php}})
        steps:
            - uses: actions/checkout@master

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php}}
                  tools: composer:v1
                  extensions: apcu, ctype, iconv, imagick, json, redis, soap, xmlreader, zip
                  coverage: none

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ matrix.php }}-composer-

            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

            - name: Unit tests
              run: phpdbg -qrr ./vendor/bin/phpunit --coverage-clover=coverage/unit.xml

    behaviour_tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.4']
        name: Behaviour tests (${{ matrix.php}})
        services:
            elasticsearch:
                image: elasticsearch:6.8.4
                ports:
                    - 9200:9200
                options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
        steps:
            # —— Check Elasticsearch 🔎 ——————————————————————————————————————————————
            - name: Check the Elasticsearch connection from runner host
              run: |
                  curl -fsSL "http://localhost:9200"
                  curl -fsSL "http://localhost:9200/_cluster/health?pretty"

            - name: Checkout
              uses: actions/checkout@master

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v1
                  extensions: apcu, ctype, iconv, imagick, json, redis, soap, xmlreader, zip
                  coverage: none

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ matrix.php }}-composer-

            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

            - name: Behaviour tests
              run: |
                  APP_ENV=test ELASTIC_URL=http://localhost:9200 bin/console fos:elastica:create
                  ELASTIC_URL=http://localhost:9200 phpdbg -d memory_limit=-1 -qrr ./vendor/bin/behat

    phpcsfixer:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            php: ['7.4']
        name: Coding style (${{ matrix.php }})
        steps:
            - uses: actions/checkout@master

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v1
                  extensions: apcu, ctype, iconv, imagick, json, redis, soap, xmlreader, zip
                  coverage: none

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v1
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: ${{ matrix.php }}-composer-

            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

            - name: PHP CS Fixer
              run: composer check-coding-standards/php-cs-fixer

            - name: Twig CS
              run: composer check-coding-standards/twigcs

    helm:
        name: Helm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: azure/setup-helm@v1
              name: Install helm
              with:
                  version: v3.1.2

            - name: Lint helm (CoverService)
              run: helm lint infrastructure/cover-service  --set hpa.enabled=true --set ingress.enableTLS=true --set ingress.mail=test@itkdev.dk --set ingress.domain=cover.dandigbib.org

            - name: Lint helm (Shared config)
              run: helm lint infrastructure/shared-config
