---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cover-service
  name: cover-service-config
data:
  APP_DB_SERVER: 'cover-service-database.mariadb.database.azure.com'
  APP_DB_PORT: '3306'
  APP_DB_DATABASE: 'cover-service'
  APP_REDIS_SERVER: 'redis'
  APP_REDIS_PORT: '6379'
  APP_ELASTIC_URL: 'https://elasticsearch-es-http:9200/'
  APP_ELASTIC_SSL: 'true'
  ELASTIC_SSL_VERIFY: 'false'

---
apiVersion: v1
kind: Service
metadata:
  namespace: cover-service
  name: cover-service
  labels:
    tier: frontend
spec:
  selector:
    app: cover-service-app
    tier: frontend
  ports:
    - protocol: TCP
      port: 9000
  type: ClusterIP

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  namespace: cover-service
  name: coverserive-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cover-service-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cover-service
  name: cover-service-app
spec:
  selector:
    matchLabels:
      app: cover-service-app
  template:
    metadata:
      labels:
        app: cover-service-app
        tier: frontend
    spec:
      imagePullSecrets:
        - name: github-registry
      containers:
      - name: coverservice
        image: docker.pkg.github.com/danskernesdigitalebibliotek/ddb-cover-service/cover-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "384Mi"
            cpu: "500m"
        readinessProbe:
          exec:
            command:
              - php-fpm-healthcheck
          initialDelaySeconds: 1
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - php-fpm-healthcheck
              #- --accepted-conn=50000
          initialDelaySeconds: 0
          periodSeconds: 10
        env:
          - name: APP_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_DB_USERNAME
          - name: APP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_DB_PASSWORD
          - name: APP_OPENPLATFORM_ID
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_OPENPLATFORM_ID
          - name: APP_OPENPLATFORM_SECRET
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_OPENPLATFORM_SECRET
          - name: APP_CLOUDINARY_ID
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_CLOUDINARY_ID
          - name: APP_CLOUDINARY_SECRET
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_CLOUDINARY_SECRET
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_SECRET
          - name: APP_ELASTIC_USERNAME
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_ELASTIC_USERNAME
          - name: APP_ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cover-service-secret
                key: APP_ELASTIC_PASSWORD
        envFrom:
          - configMapRef:
              name: cover-service-config
        ports:
          - containerPort: 9000
