---
apiVersion: v1
kind: Pod
metadata:
  name: cover-service-import
  namespace: cover-service
spec:
  imagePullSecrets:
    - name: github-registry
  containers:
  - name: coverservice
    image: docker.pkg.github.com/danskernesdigitalebibliotek/ddb-cover-service/cover-service:1.1.6
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "640Mi"
        cpu: "300m"
      limits:
        memory: "640Mi"
        cpu: "500m"
    env:
      - name: APP_DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: cover-service-secret
            key: APP_DB_USERNAME
      - name: APP_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: cover-service-secret
            key: APP_DB_PASSWORD
      - name: APP_OPENPLATFORM_ID
        valueFrom:
          secretKeyRef:
            name: cover-service-secret
            key: APP_OPENPLATFORM_ID
      - name: APP_OPENPLATFORM_SECRET
        valueFrom:
          secretKeyRef:
            name: cover-service-secret
            key: APP_OPENPLATFORM_SECRET
      - name: APP_CLOUDINARY_ID
        valueFrom:
          secretKeyRef:
            name: cover-service-secret
            key: APP_CLOUDINARY_ID
      - name: APP_CLOUDINARY_SECRET
        valueFrom:
          secretKeyRef:
            name: cover-service-secret
            key: APP_CLOUDINARY_SECRET
      - name: APP_CLOUDINARY_DOMAIN
        valueFrom:
          secretKeyRef:
            name: cover-service-secret
            key: APP_CLOUDINARY_DOMAIN
      - name: APP_SECRET
        valueFrom:
          secretKeyRef:
            name: cover-service-secret
            key: APP_SECRET
      - name: PHP_MEMORY_LIMIT
        value: "512M"
    envFrom:
      - configMapRef:
          name: cover-service-config