---
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  namespace: cover-service
  name: elasticsearch
  labels:
    tier: backend
spec:
  version: 6.8.4
  nodeSets:
    - name: cs-elasticsearch
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1024Gi
            storageClassName: managed-premium-retain
      config:
        node.master: true
        node.data: true
        node.ingest: true
      podTemplate:
        metadata:
          labels:
            tier: backend
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "9114"
            prometheus.io/scheme: "http"
        spec:
          # This changes the kernel setting on the node to allow ES to use mmap.
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                requests:
                  memory: 4Gi
                  cpu: 500m
                limits:
                  memory: 4Gi
                  cpu: 1
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx2g"
            - name: elasticsearch-exporter
                image: docker.pkg.github.com/danskernesdigitalebibliotek/ddb-cover-service/elasticsearch_exporter
                imagePullPolicy: Always
                resources:
                  requests:
                    memory: "64Mi"
                    cpu: "25m"
                  limits:
                    memory: "128Mi"
                    cpu: "100m"
                readinessProbe:
                  httpGet:
                    path: /healthz
                    port: 9114
                  initialDelaySeconds: 10
                  timeoutSeconds: 10
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 9114
                  initialDelaySeconds: 30
                  timeoutSeconds: 10
                env:
                  - name: ES_USERNAME
                    value: elastic
                  - name: ES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: elasticsearch-es-elastic-user
                        key: elastic
                ports:
                  - containerPort: 9114