---
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  namespace: cover-service
  name: elasticsearch
  labels:
    tier: backend
spec:
  version: 6.8.4
  nodeSets:
    - name: cs-elasticsearch
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 30Gi
            storageClassName: managed-premium-retain
      config:
        node.master: true
        node.data: true
        node.ingest: true
        #node.store.allow_mmap: false
      podTemplate:
        spec:
          # this changes the kernel setting on the node to allow ES to use mmap
          # if you uncomment this init container you will likely also want to remove the
          # "node.store.allow_mmap: false" setting above
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                requests:
                  memory: 3Gi
                  cpu: 500m
                limits:
                  memory: 3Gi
                  cpu: 1
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx2g"